name: Wyrmhole
options:
  bundleIdPrefix: com.wyrmhole
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  TARGETED_DEVICE_FAMILY: "2" # iPad only
  SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC.git
    from: "125.0.0"

targets:
  Wyrmhole:
    type: application
    platform: iOS
    sources:
      - path: Wyrmhole
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wyrmhole.app
        PRODUCT_NAME: Wyrmhole
        INFOPLIST_FILE: Wyrmhole/Info.plist
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: WebRTC
    entitlements:
      path: Wyrmhole/Wyrmhole.entitlements
      properties:
        com.apple.security.network.client: true
        com.apple.security.network.server: true
